### ISSUE TITLE
Servo node

### ISSUE THREAD

**Issue by fzoric8** [AndrejOrsula/panda_ign#33]
Hi,

Thanks for the awesome repository. 

I'm wondering how can I easily use `servo_node`, I've initialized it, and I'm recieving commands on: 
```
joint_trajectory_controller/joint_trajectory
```
However, arm remains stationary. 

Arm moves when I publish on follow joint trajectory action, however it remains stationary when publishing 
servo commands. 

Thank you for your help!

**Comment by AndrejOrsula** [comment]
Hello @fzoric8,

Did you call the `/servo_node/start_servo` service?

Here is one example: [pymoveit2/moveit2_servo.py#L141-L167](https://github.com/AndrejOrsula/pymoveit2/blob/7f722fd3fda6e6c958c150cf7d8ad619119d6262/pymoveit2/moveit2_servo.py#L141-L167)

**Comment by AndrejOrsula** [comment]
And a demo: [pymoveit2/examples/ex_servo.py](https://github.com/AndrejOrsula/pymoveit2/blob/7f722fd3fda6e6c958c150cf7d8ad619119d6262/examples/ex_servo.py)

**Comment by fzoric8** [comment]
@AndrejOrsula, 
I really appreciate fast response. 

After calling service, it works like charm! 

Thank you for your help :) 

_On the side note, have you tried running this on real robot?_  

Closing issue because it is solved! 
Thanks

**Comment by AndrejOrsula** [comment]
> ..., have you tried running this on real robot?

Not on a real Franka robot. Only on Kinova j2s7s300. It required a lot of servo parameter tuning but worked okay-ish.

**Comment by fzoric8** [comment]
Did you use position or velocity controller? 

Because when I used position in moveit1 it is quite laggy. 

I'm not really sure how complex is `ros2_control` but I'll try to test it on Kinova and Franka. 

Thanks for your repo, you saved me a lot of time :1st_place_medal:

**Comment by AndrejOrsula** [comment]
Position control. It was with `ros1_bridge` in the loop, using MoveIt 2 but ROS 1 controllers.
